-- V3a__Insert_motor_boat_brands_A_C.sql
-- Motor boat brands A-C (Part 1 of 6)

-- A brands
INSERT INTO brands (name, category, display_order) VALUES
('Azimut', 'MOTOR_BOATS', 1),
('Avalon', 'MOTOR_BOATS', 2),
('Axopar', 'MOTOR_BOATS', 3),
('Absolute', 'MOTOR_BOATS', 4),
('Alumacraft', 'MOTOR_BOATS', 5),
('Aquila', 'MOTOR_BOATS', 6),
('AB Inflatables', 'MOTOR_BOATS', 7),
('Avid', 'MOTOR_BOATS', 8),
('Axis', 'MOTOR_BOATS', 9),
('Aviara', 'MOTOR_BOATS', 10),
('Albemarle', 'MOTOR_BOATS', 11),
('Aquasport', 'MOTOR_BOATS', 12),
('Apreamare', 'MOTOR_BOATS', 13),
('ATX Surf Boats', 'MOTOR_BOATS', 14),
('Albin', 'MOTOR_BOATS', 15),
('Allroundmarin', 'MOTOR_BOATS', 16),
('Aicon', 'MOTOR_BOATS', 17),
('Airon', 'MOTOR_BOATS', 18),
('Alfastreet', 'MOTOR_BOATS', 19),
('ALK2 Powerboats', 'MOTOR_BOATS', 20),
('Admiral', 'MOTOR_BOATS', 21),
('Alweld', 'MOTOR_BOATS', 22),
('Anvera', 'MOTOR_BOATS', 23),
('Antaris', 'MOTOR_BOATS', 24),
('AB', 'MOTOR_BOATS', 25),
('Aquanaut', 'MOTOR_BOATS', 26),
('Aquador', 'MOTOR_BOATS', 27),
('Angler', 'MOTOR_BOATS', 28),
('Alm', 'MOTOR_BOATS', 29),
('American Tug', 'MOTOR_BOATS', 30),
('Andros', 'MOTOR_BOATS', 31),
('Arcadia Yachts', 'MOTOR_BOATS', 32),
('ACM', 'MOTOR_BOATS', 33),
('Atlantis', 'MOTOR_BOATS', 34)
ON CONFLICT (name, category) DO NOTHING;

-- B brands
INSERT INTO brands (name, category, display_order) VALUES
('Boston Whaler', 'MOTOR_BOATS', 35),
('Bayliner', 'MOTOR_BOATS', 36),
('Bennington', 'MOTOR_BOATS', 37),
('Beneteau', 'MOTOR_BOATS', 38),
('Barletta', 'MOTOR_BOATS', 39),
('Blackfin', 'MOTOR_BOATS', 40),
('Bavaria', 'MOTOR_BOATS', 41),
('Bentley Pontoons', 'MOTOR_BOATS', 42),
('Bertram', 'MOTOR_BOATS', 43),
('Brig', 'MOTOR_BOATS', 44),
('BRABUS', 'MOTOR_BOATS', 45),
('BlackJack', 'MOTOR_BOATS', 46),
('Bryant', 'MOTOR_BOATS', 47),
('Bass Tracker', 'MOTOR_BOATS', 48),
('Bombard', 'MOTOR_BOATS', 49),
('Blue Wave', 'MOTOR_BOATS', 50),
('Bluegame', 'MOTOR_BOATS', 51),
('Baia', 'MOTOR_BOATS', 52),
('Bass Cat', 'MOTOR_BOATS', 53),
('Baja', 'MOTOR_BOATS', 54),
('Back Cove', 'MOTOR_BOATS', 55),
('Blazer', 'MOTOR_BOATS', 56),
('Bluewater', 'MOTOR_BOATS', 57),
('Baglietto', 'MOTOR_BOATS', 58),
('Bali', 'MOTOR_BOATS', 59),
('Broward', 'MOTOR_BOATS', 60),
('Bay Rider', 'MOTOR_BOATS', 61),
('Birchwood', 'MOTOR_BOATS', 62),
('Benetti', 'MOTOR_BOATS', 63),
('Bulls Bay', 'MOTOR_BOATS', 64),
('Buddy Davis', 'MOTOR_BOATS', 65),
('Bahama', 'MOTOR_BOATS', 66),
('Burger', 'MOTOR_BOATS', 67),
('Boarncruiser', 'MOTOR_BOATS', 68),
('Botnia', 'MOTOR_BOATS', 69),
('Broom', 'MOTOR_BOATS', 70),
('Berkshire', 'MOTOR_BOATS', 71)
ON CONFLICT (name, category) DO NOTHING;

-- C brands
INSERT INTO brands (name, category, display_order) VALUES
('Chaparral', 'MOTOR_BOATS', 72),
('Cobalt', 'MOTOR_BOATS', 73),
('Chris-Craft', 'MOTOR_BOATS', 74),
('Cobia', 'MOTOR_BOATS', 75),
('Carver', 'MOTOR_BOATS', 76),
('Carolina Skiff', 'MOTOR_BOATS', 77),
('Cranchi', 'MOTOR_BOATS', 78),
('Crestliner', 'MOTOR_BOATS', 79),
('Crest', 'MOTOR_BOATS', 80),
('Contender', 'MOTOR_BOATS', 81),
('Custom', 'MOTOR_BOATS', 82),
('Cruisers Yachts', 'MOTOR_BOATS', 83),
('Crownline', 'MOTOR_BOATS', 84),
('Capelli', 'MOTOR_BOATS', 85),
('Caymas', 'MOTOR_BOATS', 86),
('Century', 'MOTOR_BOATS', 87),
('Cape Horn', 'MOTOR_BOATS', 88),
('Cigarette', 'MOTOR_BOATS', 89),
('Centurion', 'MOTOR_BOATS', 90),
('Cutwater', 'MOTOR_BOATS', 91),
('Canados', 'MOTOR_BOATS', 92),
('Carolina Classic', 'MOTOR_BOATS', 93),
('Cheoy Lee', 'MOTOR_BOATS', 94),
('Clearwater', 'MOTOR_BOATS', 95),
('Californian', 'MOTOR_BOATS', 96),
('Cobra Ribs', 'MOTOR_BOATS', 97),
('Concept', 'MOTOR_BOATS', 98),
('CHB', 'MOTOR_BOATS', 99),
('Corsiva', 'MOTOR_BOATS', 100),
('Cormate', 'MOTOR_BOATS', 101),
('Cypress Cay', 'MOTOR_BOATS', 102),
('Caravelle', 'MOTOR_BOATS', 103),
('Classic', 'MOTOR_BOATS', 104),
('Champion', 'MOTOR_BOATS', 105),
('Cantieri di Pisa', 'MOTOR_BOATS', 106),
('Cayman Yachts', 'MOTOR_BOATS', 107),
('Colombo', 'MOTOR_BOATS', 108)
ON CONFLICT (name, category) DO NOTHING;