-- V3d__Insert_motor_boat_brands_N_S.sql
-- Motor boat brands N-S (Part 4 of 6)

-- N brands
INSERT INTO brands (name, category, display_order) VALUES
('NX Boats', 'MOTOR_BOATS', 251),
('Native Watercraft', 'MOTOR_BOATS', 252),
('NauticStar', 'MOTOR_BOATS', 253),
('Nautique', 'MOTOR_BOATS', 254),
('Navan', 'MOTOR_BOATS', 255),
('Navigator', 'MOTOR_BOATS', 256),
('Neptunus', 'MOTOR_BOATS', 257),
('Nimbus', 'MOTOR_BOATS', 258),
('Nireus', 'MOTOR_BOATS', 259),
('Nitro', 'MOTOR_BOATS', 260),
('Nor-Tech', 'MOTOR_BOATS', 261),
('Nord Star', 'MOTOR_BOATS', 262),
('Nordhavn', 'MOTOR_BOATS', 263),
('Nordic Tug', 'MOTOR_BOATS', 264),
('Nordkapp', 'MOTOR_BOATS', 265),
('North River', 'MOTOR_BOATS', 266),
('NorthCoast', 'MOTOR_BOATS', 267),
('Northstar', 'MOTOR_BOATS', 268),
('Novamarine', 'MOTOR_BOATS', 269),
('Novurania', 'MOTOR_BOATS', 270),
('Numarine', 'MOTOR_BOATS', 271),
('Nuova Jolly', 'MOTOR_BOATS', 272)
ON CONFLICT (name, category) DO NOTHING;

-- O brands
INSERT INTO brands (name, category, display_order) VALUES
('Ocean Alexander', 'MOTOR_BOATS', 273),
('Ocean Craft Marine', 'MOTOR_BOATS', 274),
('Ocean Yachts', 'MOTOR_BOATS', 275),
('Ocqueteau', 'MOTOR_BOATS', 276),
('Omega', 'MOTOR_BOATS', 277),
('Offshore Yachts', 'MOTOR_BOATS', 278),
('Outer Reef Yachts', 'MOTOR_BOATS', 279)
ON CONFLICT (name, category) DO NOTHING;

-- P brands
INSERT INTO brands (name, category, display_order) VALUES
('Pacific', 'MOTOR_BOATS', 280),
('Pacific Craft', 'MOTOR_BOATS', 281),
('Pair Customs', 'MOTOR_BOATS', 282),
('Palm Beach Motor Yachts', 'MOTOR_BOATS', 283),
('Pardo Yachts', 'MOTOR_BOATS', 284),
('Parker', 'MOTOR_BOATS', 285),
('Parker Poland', 'MOTOR_BOATS', 286),
('Pathfinder', 'MOTOR_BOATS', 287),
('Pearl', 'MOTOR_BOATS', 288),
('Pedro', 'MOTOR_BOATS', 289),
('Pershing', 'MOTOR_BOATS', 290),
('Phoenix', 'MOTOR_BOATS', 291),
('Pioneer', 'MOTOR_BOATS', 292),
('Pirelli', 'MOTOR_BOATS', 293),
('Polar Kraft', 'MOTOR_BOATS', 294),
('Posillipo', 'MOTOR_BOATS', 295),
('Post', 'MOTOR_BOATS', 296),
('Premier', 'MOTOR_BOATS', 297),
('President', 'MOTOR_BOATS', 298),
('Prestige', 'MOTOR_BOATS', 299),
('Princecraft', 'MOTOR_BOATS', 300),
('Princess', 'MOTOR_BOATS', 301),
('Pro-Line', 'MOTOR_BOATS', 302),
('Pro Marine', 'MOTOR_BOATS', 303),
('Protector', 'MOTOR_BOATS', 304),
('Pursuit', 'MOTOR_BOATS', 305)
ON CONFLICT (name, category) DO NOTHING;

-- Q brands
INSERT INTO brands (name, category, display_order) VALUES
('Qwest', 'MOTOR_BOATS', 306),
('Quarken', 'MOTOR_BOATS', 307),
('Quicksilver', 'MOTOR_BOATS', 308)
ON CONFLICT (name, category) DO NOTHING;

-- R brands
INSERT INTO brands (name, category, display_order) VALUES
('RIO', 'MOTOR_BOATS', 309),
('RYCK', 'MOTOR_BOATS', 310),
('Rampage', 'MOTOR_BOATS', 311),
('Rand', 'MOTOR_BOATS', 312),
('Ranger', 'MOTOR_BOATS', 313),
('Ranger Tugs', 'MOTOR_BOATS', 314),
('Ranieri', 'MOTOR_BOATS', 315),
('Reaper Boats', 'MOTOR_BOATS', 316),
('Regal', 'MOTOR_BOATS', 317),
('Regency', 'MOTOR_BOATS', 318),
('Regulator', 'MOTOR_BOATS', 319),
('Release', 'MOTOR_BOATS', 320),
('Rhea', 'MOTOR_BOATS', 321),
('Ribco', 'MOTOR_BOATS', 322),
('Ribeye', 'MOTOR_BOATS', 323),
('Rinker', 'MOTOR_BOATS', 324),
('Rio Yachts', 'MOTOR_BOATS', 325),
('Riva', 'MOTOR_BOATS', 326),
('Riviera', 'MOTOR_BOATS', 327),
('Rizzardi', 'MOTOR_BOATS', 328),
('Robalo', 'MOTOR_BOATS', 329),
('Rodman', 'MOTOR_BOATS', 330),
('Rybovich', 'MOTOR_BOATS', 331)
ON CONFLICT (name, category) DO NOTHING;

-- S brands (Part 1)
INSERT INTO brands (name, category, display_order) VALUES
('SACS', 'MOTOR_BOATS', 332),
('Sabre', 'MOTOR_BOATS', 333),
('Saga', 'MOTOR_BOATS', 334),
('Sailfish', 'MOTOR_BOATS', 335),
('Salpa', 'MOTOR_BOATS', 336),
('Sanger', 'MOTOR_BOATS', 337),
('Sanlorenzo', 'MOTOR_BOATS', 338),
('Sargo', 'MOTOR_BOATS', 339),
('Sasga Yachts', 'MOTOR_BOATS', 340),
('Savannah', 'MOTOR_BOATS', 341),
('Saver', 'MOTOR_BOATS', 342),
('Saxdor', 'MOTOR_BOATS', 343),
('Scanner', 'MOTOR_BOATS', 344),
('Scarab', 'MOTOR_BOATS', 345),
('Schaefer', 'MOTOR_BOATS', 346),
('Scorpion', 'MOTOR_BOATS', 347),
('Scout', 'MOTOR_BOATS', 348),
('Sea Ark', 'MOTOR_BOATS', 349),
('Sea Born', 'MOTOR_BOATS', 350),
('Sea Cat', 'MOTOR_BOATS', 351),
('Sea Chaser', 'MOTOR_BOATS', 352),
('Sea Fox', 'MOTOR_BOATS', 353),
('Sea Hunt', 'MOTOR_BOATS', 354),
('Sea Pro', 'MOTOR_BOATS', 355),
('Sea Ray', 'MOTOR_BOATS', 356),
('Sea Water', 'MOTOR_BOATS', 357),
('Sea-Doo Sport Boats', 'MOTOR_BOATS', 358),
('SeaCraft', 'MOTOR_BOATS', 359),
('SeaHunter', 'MOTOR_BOATS', 360),
('SeaVee', 'MOTOR_BOATS', 361),
('Sealine', 'MOTOR_BOATS', 362),
('Seaswirl', 'MOTOR_BOATS', 363),
('Seaswirl Striper', 'MOTOR_BOATS', 364),
('Sessa Marine', 'MOTOR_BOATS', 365),
('Shallow Sport', 'MOTOR_BOATS', 366),
('Shamrock', 'MOTOR_BOATS', 367),
('ShearWater', 'MOTOR_BOATS', 368),
('Shoalwater', 'MOTOR_BOATS', 369),
('Silverton', 'MOTOR_BOATS', 370),
('Sirena', 'MOTOR_BOATS', 371),
('Skeeter', 'MOTOR_BOATS', 372),
('Skipper-BSK', 'MOTOR_BOATS', 373),
('Sloep', 'MOTOR_BOATS', 374),
('Smartliner', 'MOTOR_BOATS', 375),
('Smoker Craft', 'MOTOR_BOATS', 376),
('Solace', 'MOTOR_BOATS', 377),
('Solara', 'MOTOR_BOATS', 378),
('Solaris Power', 'MOTOR_BOATS', 379),
('South Bay', 'MOTOR_BOATS', 380),
('SouthWind', 'MOTOR_BOATS', 381),
('Southport', 'MOTOR_BOATS', 382),
('Spartan', 'MOTOR_BOATS', 383),
('Sportsman', 'MOTOR_BOATS', 384),
('Stabicraft', 'MOTOR_BOATS', 385),
('Stamas', 'MOTOR_BOATS', 386),
('Starcraft', 'MOTOR_BOATS', 387),
('Stardust Cruisers', 'MOTOR_BOATS', 388),
('Starfisher', 'MOTOR_BOATS', 389),
('Starweld', 'MOTOR_BOATS', 390),
('Statement', 'MOTOR_BOATS', 391),
('Steiger Craft', 'MOTOR_BOATS', 392),
('Stingray', 'MOTOR_BOATS', 393),
('Storebro', 'MOTOR_BOATS', 394),
('Stratos', 'MOTOR_BOATS', 395),
('Sublue', 'MOTOR_BOATS', 396),
('Sumerset', 'MOTOR_BOATS', 397),
('Sun Tracker', 'MOTOR_BOATS', 398),
('SunCatcher', 'MOTOR_BOATS', 399),
('SunChaser', 'MOTOR_BOATS', 400),
('Sundance', 'MOTOR_BOATS', 401),
('Sunreef', 'MOTOR_BOATS', 402),
('Sunsation', 'MOTOR_BOATS', 403),
('Sunseeker', 'MOTOR_BOATS', 404),
('Super Van Craft', 'MOTOR_BOATS', 405),
('Supra', 'MOTOR_BOATS', 406),
('Supreme', 'MOTOR_BOATS', 407),
('Sweetwater', 'MOTOR_BOATS', 408),
('Sylvan', 'MOTOR_BOATS', 409),
('Symbol', 'MOTOR_BOATS', 410),
('Suzuki Suzumar', 'MOTOR_BOATS', 411)
ON CONFLICT (name, category) DO NOTHING;